[package]
name = "myaxum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
tokio = { version = "1.33.0", features = ["full"] }
scrypt = "0.11.0"
jsonwebtoken = "9"
serde = { version = "1.0", features = ["derive"] }
surrealdb = { version = "1.3.0" }
